export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_STUDENT = "GET_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT ";

export const GET_ALL_PARENTS = "GET_ALL_PARENTS";
export const GET_PARENT = "GET_PARENT";
export const UPDATE_PARENT = "UPDATE_PARENT";
export const DELETE_PARENT = "DELETE_PARENT";

export const SET_USER_ACTIVE = "SET_USER_ACTIVE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
